# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4f055221f19ed6fe2a670d8dc9a49b51c227d3cccdf8995693c57738b7a538beeb175f87299e81a5a071becd04963485c9744417e7f8f26128ea99d870a89124

test:
  secret_key_base: 463ded5782c54e2d31dc60e015ea735d378fd4714a0633e83f1a6d13963817b249382032f42e8b407d8cd4053e1ac6cc516d83a7292aa01f66042300eca52b2e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
